[2024-10-22T14:43:46.051+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-22T14:43:46.071+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_football.extract_data_wiki manual__2024-10-22T14:43:45.126039+00:00 [queued]>
[2024-10-22T14:43:46.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_football.extract_data_wiki manual__2024-10-22T14:43:45.126039+00:00 [queued]>
[2024-10-22T14:43:46.076+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-22T14:43:46.083+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_wiki> on 2024-10-22 14:43:45.126039+00:00
[2024-10-22T14:43:46.090+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_football', 'extract_data_wiki', 'manual__2024-10-22T14:43:45.126039+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_football.py', '--cfg-path', '/tmp/tmp9c3hixus']
[2024-10-22T14:43:46.092+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask extract_data_wiki
[2024-10-22T14:43:46.093+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=720) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-22T14:43:46.093+0000] {standard_task_runner.py:64} INFO - Started process 722 to run task
[2024-10-22T14:43:46.124+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_football.extract_data_wiki manual__2024-10-22T14:43:45.126039+00:00 [running]> on host 884be59c9e77
[2024-10-22T14:43:46.172+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Karan' AIRFLOW_CTX_DAG_ID='dag_football' AIRFLOW_CTX_TASK_ID='extract_data_wiki' AIRFLOW_CTX_EXECUTION_DATE='2024-10-22T14:43:45.126039+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-22T14:43:45.126039+00:00'
[2024-10-22T14:43:46.174+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-22T14:43:46.346+0000] {logging_mixin.py:188} INFO - An error occured : HTTPSConnectionPool(host='en.wikipedia.org', port=443): Max retries exceeded with url: /wiki/List_of_association_football_stadiums_by_capacity (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))
[2024-10-22T14:43:46.347+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-22T14:43:46.348+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/get_wiki_data.py", line 14, in get_wiki_data
    soup = BeautifulSoup(html,features='html.parser')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
[2024-10-22T14:43:46.357+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_football, task_id=extract_data_wiki, run_id=manual__2024-10-22T14:43:45.126039+00:00, execution_date=20241022T144345, start_date=20241022T144346, end_date=20241022T144346
[2024-10-22T14:43:46.365+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task extract_data_wiki (object of type 'NoneType' has no len(); 722)
[2024-10-22T14:43:46.388+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-22T14:43:46.398+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-22T14:43:46.400+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
